version: 0.1.11.{build}
branches:
  only:
  - release
image: Visual Studio 2022
configuration: Release
install:
  - cmd: >-
        cd %APPVEYOR_BUILD_FOLDER% 
        && git submodule update --init --recursive
nuget:  
  project_feed: true
before_build:
- cmd: "cd %APPVEYOR_BUILD_FOLDER% \nnuget restore"
build:
  publish_nuget: true  
  verbosity: minimal
after_build:
- cmd: ''
before_deploy:
- cmd: ''
deploy:
- provider: NuGet
  api_key:
    secure: 5Pn6/9YO/1e0Je0kfJqLuDmDaUnRelV1Zc72SRKyZ/nU1mbOT4X6dkJwaTC8DVBE
  on:
    branch: release