version: 0.1.7.{build}
branches:
  only:
  - release
image: Visual Studio 2019
configuration: Release
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_core_console: true
  verbosity: minimal
after_build:
- cmd: build_package.cmd
before_deploy:
- cmd: ''
deploy:
- provider: NuGet
  api_key:
    secure: M0Z+oXx6GiMe4j9VljY+OGVAAwjpZ4Ri5EohgoqTa+X24xXCAu59jQZcJBNhf6cr
  on:
    branch: release