version: 0.1.9.{build}
branches:
  only:
  - release
image: Visual Studio 2019
configuration: Release
install:
  - ps: cd %APPVEYOR_BUILD_FOLDER% 
        git submodule update --init --recursive
nuget:
  account_feed: true
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true  
  verbosity: minimal
after_build:
- cmd: build_package.cmd
before_deploy:
- cmd: ''
deploy:
- provider: NuGet
  api_key:
    secure: EunKamGcsJ3kXIvrtT60bbQrXQtO8dhZV29AuDpKLls=
  on:
    branch: release