name: Build

on:
  push:
    branches: [ github-readme ]  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
        
    - name: Adding README - Chinese Simplified
      uses: dephraiim/translate-readme@main
      with:
        LANG: zh-CN